Repository corteva/rioxarray, pull requests merged in 2024-10, with the labels that each got.

#807 CI: pin micromamba
  .github/workflows/build_docs.yaml
  .github/workflows/tests.yaml
Labels: cicd

#808 CI: Add libgdal for micromamba tests
  .github/workflows/tests.yaml
  environment.yml
Labels: cicd

#810 BUG: Squeeze when using interpolate_na with extra dim
  rioxarray/raster_array.py
Labels: bug

#811 DOC: Clearer docstring for `open_rasterio`
  rioxarray/_io.py
Labels: documentation

#819 DEP: xarray>=2024.7
  .github/workflows/tests.yaml
  pyproject.toml
Labels: dependencies
