Repository corteva/rioxarray, pull requests merged in 2024-07, with the labels that each got.

#792 docs: fix minor code block issue for local installation in CONTRIBUTING.rst
  CONTRIBUTING.rst
Labels: documentation

#796 ENH: Add allow_one_dimensional_raster option to rio.clip_box
  docs/history.rst
  rioxarray/raster_array.py
  rioxarray/raster_dataset.py
  test/integration/test_integration_rioxarray.py
Labels: enhancement

#793 MNT: recommend write_crs & deprecate set_crs
  docs/getting_started/crs_management.ipynb
  rioxarray/rioxarray.py
Labels: bug, documentation

#798 CI: Remove apache arrow apt sources
  .github/workflows/tests.yaml
Labels: cicd
