Repository corteva/rioxarray, pull requests merged in 2024-06, with the labels that each got.

#782 BUG: Raise overflow error when nodata conversion is unsafe
  docs/history.rst
  rioxarray/raster_writer.py
  test/integration/test_integration_rioxarray.py
Labels: bug

#783 CI: use macos-13 runner
  .github/workflows/tests.yaml
Labels: cicd

#784 DOC: multiple types
  rioxarray/merge.py
Labels: documentation

#786 CI: Fix latest test environment setup
  .github/workflows/tests.yaml
Labels: cicd

#785 CI: Add numpy-version pin
  .github/workflows/tests.yaml
Labels: cicd

#787 BUG: Support writing GCPs to netCDF
  docs/history.rst
  rioxarray/rioxarray.py
  test/integration/test_integration__io.py
  test/integration/test_integration_rioxarray.py
Labels: bug

#790 BUG: Remove grid_mapping from attrs when writing
  docs/history.rst
  rioxarray/rioxarray.py
  test/integration/test_integration_rioxarray.py
Labels: bug
