Repository corteva/rioxarray, pull requests merged in 2024-11, with the labels that each got.

#817 BUG:merge: Fix merging masked & scaled data
  .github/workflows/tests.yaml
  docs/history.rst
  rioxarray/_io.py
  rioxarray/merge.py
  test/integration/test_integration_merge.py
Labels: bug

#820 BUG: Fix chunk arguments for normalize_chunks
  rioxarray/_io.py
Labels: bug

#826 CI: Update GDAL & Python tested versions
  .github/workflows/tests.yaml
  docs/history.rst
  pyproject.toml
Labels: cicd, test

#828 BUG:merge: Ensure dims and coords match input array
  docs/history.rst
  rioxarray/merge.py
  test/integration/test_integration_merge.py
Labels: bug

#830 Fix typo in raster_array.py
  rioxarray/raster_array.py
Labels: bug, documentation

#834 DOC: Update warning message for differing scales in rasterio attributes
  rioxarray/_io.py
Labels: bug, documentation
